web:
  image: 'gitlab/gitlab-ee:latest'
  container_name: 'edu_gitlab'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.gmail.com"
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = "user@gmail.com"
      gitlab_rails['smtp_password'] = "app-password"
      gitlab_rails['smtp_domain'] = "smtp.gmail.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '8880:80'
    - '9443:443'
    - '8822:22'
    - '8587:587'
  volumes:
    - '/Users/tuananh/Projects/docker/gitlab/gitlab/config:/etc/gitlab'
    - '/Users/tuananh/Projects/docker/gitlab/gitlab/logs:/var/log/gitlab'
    - '/Users/tuananh/Projects/docker/gitlab/gitlab/data:/var/opt/gitlab'
