version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    ports:
      - 9981:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /Users/tuananh/Projects/docker/jenkins_docker/jenkins/var/jenkins_home
      - /Users/tuananh/Projects/docker/jenkins_docker/jenkins/var/run/docker.sock:/var/run/docker.sock
      - /Users/tuananh/Projects/docker/jenkins_docker/jenkins/usr/local/bin/docker:/usr/local/bin/docker
      - /Users/tuananh/Projects/docker/jenkins_docker/ssh:/root/.ssh/
